### ISSUE TITLE
Treat posting body to markdown to preserve formatting.

### ISSUE THREAD

**Issue by Genora** [quenktechnologies/board#35]
![Screen Shot 2020-09-10 at 6 20 55 PM](https://user-images.githubusercontent.com/64547657/92815779-8fb4ff80-f392-11ea-8251-39f6b4b54379.png)

Paragraph spacing is lost in the output/ final view

**Comment by metasansana** [comment]
We can use this tool to convert the text:
https://github.com/markedjs/marked

**Comment by metasansana** [comment]
This was more or less implemented. Could be better but we'll stick with what we have for now.
